config/routes.rb
Rails.application.routes.draw do

resources :products do
  resources :reviews, only: [:show, :create, :destroy]
end
resources :users, only: [:new, :create, :show, :update]
resources :sessions, only: [:new, :create, :destroy]

root "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: 8..20

  has_many :reviews, dependent: :destroy
  has_many :products
  has_many :reviewed_products, class_name: "Product", through: :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in to complete this action."
      redirect_to new_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :ensure_logged_in, only: [:create, :edit, :update, :destroy]
  before_filter :product_find, only: [:show, :edit, :update, :destroy]

  def index
    @products = if params[:search] 
      Product.where('LOWER(name) LIKE LOWER(?)', "%#{params[:search]}%").page(params[:page])
    else
      Product.order('products.created_at DESC').page(params[:page])
    end

    respond_to :html, :js

    @product = Product.new

    @user = User.find_by(session[:user_id])
  end

  def show
    @reviews = Product.find(params[:id]).reviews

    if current_user
      @new_review = @product.reviews.build
    end

    respond_to do |format|
      format.html 
      format.js
    end    
  end

  def new
    @product = Product.new
  end

  def edit

  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    if @product.save
      respond_to do |format|
        format.html {
          redirect_to product_path(@product)
        }
        format.js
      end
    else
      render :new, alert: "Something went wrong!"
    end


  end

  def update
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else 
      render :edit, alert: "Something went wrong!"
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path

  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

  def product_find
    @product = Product.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      flash[:notice] = "Review saved!"
      redirect_to product_path(@product)
    else
      render "/products/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to product_path(@product)
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, notice: "Logged in"
    else 
      alert: "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Signed up!"
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <p class="user_info">
  <% if current_user %>
    Welcome, <%= link_to current_user.first_name.capitalize, user_path(current_user) %>! <%= link_to "Log out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %> or <%= link_to "Log in", new_session_path %>
    <% end %>
  </p>

  <%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(product, :remote => true, id: "new_product") do |p| %>
  <% if product.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(product.errors.count, "error") %> prevented this product from being saved:</h3>

    <ul>
      <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= p.label :name %><br>
    <%= p.text_field :name %>
  </div>
  <div class="field">
    <%= p.label :price_in_cents %><br>
    <%= p.text_field :price_in_cents %>
  </div>
  <div class="field">
    <%= p.label :description %><br>
    <%= p.text_area :description %>
  </div>
  <div class="actions submit"><%= p.submit "Submit" %></div><br>
<% end %>

app/views/products/_product.html.erb
<div class='product'>
  <h2><%= link_to product.name, product_path(product) %></h2>
  <h5>$<%= product.formatted_price %></h5> 
  <p><%= product.description %></p>
  <p><%= product.reviews.count %> reviews</p>
  <p><%= link_to "See more…", product_path(product) %></p>
</div>

app/views/products/create.js.erb
$('#all_products').prepend("<%= j(render @product) %>");
$('#product_form').toggle();
$('#product_form').find('input:text, textarea').val('');

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render partial: 'form', locals: {product: @product} %>

app/views/products/index.html.erb
<h1><%= link_to "All Products", products_path %></h1>

<%= form_tag products_path, method: :get, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search!" %>
<% end %>

<div id="new_product_div"><% if current_user %>
  <h3><%= link_to("Add new product", new_product_path, id: "add_new_product") %></h3>
  <div id="product_form" >
    <%= render partial: 'form', locals: {product: Product.new} %>
  </div>
  <% end %>
</div>

<div id="all_products">
  <%= render @products || "No products match that search!" %>
</div>

<%= paginate @products %>

app/views/products/index.js.erb
$('.pagination').replaceWith("<%= j(paginate @products) %>");

app/views/products/new.html.erb
<h1>Add new product</h1>

<div id ="add_new">
  <%= render "form", locals: {product: @product} %>
</div>

<%= link_to "Back to all products", products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h4>$<%= @product.formatted_price %></h4>
<p><%= @product.description %></p>

<h3>Reviews</h3>
<div id="reviews">
  <%= render @reviews if reviews.count > 0 %>
</div>

<h4>Add a review:</h4>
<% if current_user %>
  <%= render :partial => 'reviews/form', locals: {product: @product, review: @new_review} %>
<% else %> 
  <p><%= link_to "Sign up", new_user_path %> or <%= link_to "log in", new_session_path %> to add a review for this product.</p>
<% end %>



<p><% if current_user %>
  <% if @product.user_id == current_user.id %>
  <%= link_to "Edit Product", edit_product_path(@product) %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Delete Product", @product, :method => :delete %>
<% end %><% end %></p>
<p><%= link_to "Back to all Products", products_path %></p>

app/views/reviews/_form.html.erb
<%= form_for([product, review], :remote => true) do |f| %>
  <% if review.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in review.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div> 
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions" id="submit_review"><%= f.submit "Submit" %></div>
<% end %>

app/views/reviews/_review.html.erb
<div>
      <p><% if review.user != nil %>
        <strong><%= link_to ("#{review.user.first_name} #{review.user.last_name}"), user_path(review.user) %></strong><br>
        <%= review.comment %><br>
        <em>Added on <%= review.created_at.to_date %></em>
        <% if review.user == current_user %>
          <%= link_to "Delete review", [@product, review], :method => :delete %>
        <% end %></p>
      <% end %>

    <!-- <p>This product has no reviews yet.</p> -->

</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Please try again</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign up!" %></div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h1>
<h5>Est. <%= @user.created_at.to_date %></h5>

<h3>Products added</h3>
<p><%= @user.first_name.capitalize %> has added <%= @user.products.count %> <%= "product".pluralize(@user.products.count) %>.</p>

<div class="display_products">
  <% if @user.products.count > 0 %>
    <% @user.products.each do |product| %>
    <p><strong><%= link_to product.name, product_path %></strong><br>
      <%= product.description %>
    </p>
    <% end %>
  <% end %>
</div>

<h3>Reviews</h3>

<p><%= @user.first_name.capitalize %> has reviewed <%= @user.reviews.count %> <%= "product".pluralize(@user.reviews.count) %>.</p>

<div class="reviews">
  <% if @user.reviews.count > 0 %>
    <% @user.reviews.each do |review| %>
      <p><strong><%= link_to review.product.name, product_path(review.product) %></strong><br>
      <%= review.comment %></p>
    <% end %>
  <% end %>
</div>

<%= link_to "Back to all products", products_path %>